# Imagem de Origem
FROM node:13-alpine
# Diretório de trabalho(é onde a aplicação ficará dentro do container).
WORKDIR /client
# Adicionando `/client/node_modules/.bin` para o $PATH
ENV PATH /client/node_modules/.bin:$PATH
# Instalando dependências da aplicação e armazenando em cache.
COPY . /client/
RUN yarn install --silent
RUN yarn global add react-scripts@3.3.1 --silent
# start app
CMD ["yarn", "start"]