version: '2'
services:
  mongo:
    build:
      context: .
      dockerfile: mongo.dockerfile
    ports:
      - "27017:27017"

    # command: mongoimport --host locahost --db graphl --collection customers --type json --file /customers.json --jsonArray