type Customer {
	_id: ID!
	first_name: String!
	last_name: String!
	email: String!
	gender: String!
	company: String!
	city: String!
	title: String!
	lat: String
	long: String
}

type Total {
	city: String!
	customers_total: Int!
}

type Query {
	totalCustomersByCity: [Total]!
	customer(id: ID!): Customer
	customersByCity(city: String!, pageSize: Int, after: String):CustomerByCityConnection!
}

type CustomerByCityConnection {
  cursor: String!
  hasMore: Boolean!
  customers: [Customer]!
}